// Generated by CoffeeScript 1.11.1
(function() {
  var getOptions, saveOptions;

  saveOptions = function() {
    var data;
    data = {
      username: document.getElementById("username").value,
      quantity: document.getElementById("number_of_emails").value,
      provider: document.getElementById("provider").value
    };
    chrome.storage.local.set(data, function() {
      var status;
      status = document.getElementById('status');
      status.textContent = 'Options saved.';
    });
  };

  getOptions = function() {
    var data;
    data = {
      username: '',
      quantity: 3,
      provider: ''
    };
    chrome.storage.local.get(data, function(items) {
      document.getElementById('username').value = items.username;
      document.getElementById('number_of_emails').value = items.quantity;
      document.getElementById('provider').value = items.provider;
    });
  };

  document.addEventListener("DOMContentLoaded", getOptions);

  document.getElementById("save").addEventListener("click", saveOptions);

}).call(this);

//# sourceMappingURL=options.js.map
